import http from 'node:http';
import {readFile,mkdir,writeFile} from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
import path from 'node:path';
import {randomUUID} from 'node:crypto';
const root=path.join(path.dirname(fileURLToPath(import.meta.url)),'public');
const dataDir=process.env.DATA_DIR||path.join(path.dirname(root),'data');
const origin=process.env.PUBLIC_ORIGIN||'http://localhost:3000';
const limits=new Map();
const types={'.html':'text/html; charset=utf-8','.css':'text/css; charset=utf-8','.js':'text/javascript; charset=utf-8','.svg':'image/svg+xml','.jpg':'image/jpeg','.txt':'text/plain; charset=utf-8','.xml':'application/xml'};
function json(res,status,data){res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'});res.end(JSON.stringify(data))}
const dateOk=v=>typeof v==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(v)&&!isNaN(Date.parse(v))&&new Date(v).toISOString().slice(0,10)===v;
export function validate(d){if(!d||typeof d!=='object'||Array.isArray(d))return 'Geçersiz form.';const lengths={destination:150,departure:100,name:100,email:254,phone:30,notes:1500,language:2};for(const [k,max] of Object.entries(lengths)){if(d[k]!=null&&(typeof d[k]!=='string'||d[k].length>max))return 'Lütfen alan uzunluklarını kontrol edin.'}for(const k of ['destination','departure','name','email'])if(!d[k]?.trim())return 'Lütfen zorunlu alanları doldurun.';if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(d.email))return 'Geçerli bir e-posta adresi girin.';if(!dateOk(d.start)||!dateOk(d.end)||d.end<d.start||d.start<new Date(Date.now()-86400000).toISOString().slice(0,10))return 'Geçerli seyahat tarihleri seçin.';if(!Number.isInteger(Number(d.people))||Number(d.people)<1||Number(d.people)>50)return 'Kişi sayısı 1–50 arasında olmalı.';if(!Number.isFinite(Number(d.budget))||Number(d.budget)<=0||Number(d.budget)>100000000)return 'Geçerli bir bütçe girin.';for(const [k,options]of Object.entries({currency:['EUR','TRY','USD','GBP'],package:['citytrip','itinerant','sedentary','undecided','Keşif','İmza','Özel Rota','Birlikte seçelim'],pace:['Dengeli: keşif ve dinlenme','Sakin: acele etmeden','Yoğun: mümkün olduğunca çok yer'],stay:['Otel ve kiralık ev seçeneklerine açığım','Otel','Kiralık ev / apart','Butik konaklama']}))if(!options.includes(d[k]))return 'Lütfen geçerli tercihler seçin.';if(d.language!=null&&!['fr','en','tr'].includes(d.language))return 'Invalid language.';if(d.consent!==true)return 'İletişim talebini onaylayın.';return null}
export const server=http.createServer(async(req,res)=>{res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('Referrer-Policy','strict-origin-when-cross-origin');res.setHeader('X-Frame-Options','DENY');res.setHeader('Content-Security-Policy',"default-src 'self'; img-src 'self'; style-src 'self'; script-src 'self'; connect-src 'self'; object-src 'none'; base-uri 'none'; frame-ancestors 'none'; form-action 'self'");res.setHeader('Permissions-Policy','camera=(), microphone=(), geolocation=()');try{const url=new URL(req.url,'http://localhost');if(url.pathname==='/healthz')return json(res,200,{ok:true});if(url.pathname==='/api/inquiries'){if(req.method!=='POST')return json(res,405,{error:'Yöntem desteklenmiyor.'});if(req.headers.origin!==origin)return json(res,403,{error:'İstek kaynağı doğrulanamadı.'});if(!req.headers['content-type']?.startsWith('application/json'))return json(res,415,{error:'Geçersiz içerik türü.'});const ip=process.env.TRUST_PROXY==='1'?(req.headers['x-real-ip']||req.socket.remoteAddress):req.socket.remoteAddress;const now=Date.now();for(const [key,value]of limits)if(value.until<now)limits.delete(key);const rate=limits.get(ip)||{count:0,until:now+3600000};if(rate.count>=10)return json(res,429,{error:'Çok fazla deneme. Lütfen daha sonra tekrar deneyin.'});rate.count++;limits.set(ip,rate);let body='';for await(const chunk of req){body+=chunk;if(Buffer.byteLength(body)>16384)return json(res,413,{error:'Form çok büyük.'})}let d;try{d=JSON.parse(body)}catch{return json(res,400,{error:'Geçersiz form.'})}if(d?.website)return json(res,400,{error:'Talep doğrulanamadı.'});const error=validate(d);if(error)return json(res,422,{error});const id='EV-'+randomUUID();const record={id,createdAt:new Date().toISOString()};for(const k of ['destination','departure','start','end','people','package','budget','currency','pace','stay','notes','name','email','phone','consent','language'])record[k]=typeof d[k]==='string'?d[k].trim():d[k];await mkdir(dataDir,{recursive:true,mode:0o700});await writeFile(path.join(dataDir,id+'.json'),JSON.stringify(record,null,2),{mode:0o600,flag:'wx'});return json(res,201,{id})}if(req.method!=='GET'&&req.method!=='HEAD'){res.writeHead(405);return res.end()}const pathname=decodeURIComponent(url.pathname);const file=path.resolve(root,'.'+(pathname==='/'?'/index.html':pathname));if(!file.startsWith(root+path.sep)||pathname.includes('\0')){res.writeHead(404);return res.end('Not found')}try{const content=await readFile(file);res.writeHead(200,{'Content-Type':types[path.extname(file)]||'application/octet-stream','Cache-Control':file.endsWith('.html')?'no-cache':'public, max-age=3600'});res.end(req.method==='HEAD'?undefined:content)}catch{res.writeHead(404);res.end('Not found')}}catch{json(res,500,{error:'Talep kaydedilemedi. Lütfen tekrar deneyin.'})}});
if(process.argv[1]===fileURLToPath(import.meta.url)){server.listen(Number(process.env.PORT)||3000,'0.0.0.0',()=>console.log('Elmas Voyages listening'));}
